### ISSUE TITLE
Corpse Emperor

### ISSUE THREAD

**Issue by HHound** [jpenlan/ARTG-129-Gey_Vampire_Masquerade#11]

**Comment by HazyHermit** [comment]
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/95469946/88e7f151-b6bd-4f13-8eba-aa6aef6c0e9a)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/95469946/4d353e3f-f219-48b9-add6-37d38bbd6f83)
