### ISSUE TITLE
Monster Concept - Sirens

### ISSUE THREAD

**Issue by MetaToshi** [jpenlan/ARTG-129-Gey_Vampire_Masquerade#32]

**Comment by Aismagil** [comment]
Some ideas for the siren.
![7653FF3A-ECE9-48F5-8366-2E020641354A](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/102846105/8ecb7053-70ea-4015-b223-eed8c588d0b5)
![D9DF7A88-B428-49A1-ACB4-5E287D53F17E](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/102846105/3334ae38-7317-4e47-a604-2b83166ff1c4)
