### ISSUE TITLE
Cassian - sprites

### ISSUE THREAD

**Issue by HazyHermit** [jpenlan/ARTG-129-Gey_Vampire_Masquerade#55]

**Comment by HHound** [comment]
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/b5b5ccb6-5b1d-4459-a1a5-0569559d4f44)



![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/d77e8bd1-e79c-4291-99f8-adc5437eeb5b)



![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/bf9499bc-a26b-486b-83a9-6c4eea3af15c)



![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/522223d9-e667-40ef-8bf1-491494d4a01f)



![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/39645cfd-713b-4181-b09b-73f7d80f331a)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/dd06925a-aca3-44e5-a5af-d2e4d26f0b7c)



![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/c11b325f-f116-4ddc-86aa-75ee5bc37306)
