### ISSUE TITLE
Corpse Emperor Coloring

### ISSUE THREAD

**Issue by HHound** [jpenlan/ARTG-129-Gey_Vampire_Masquerade#59]

**Comment by HHound** [comment]
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/a20f7941-6155-498c-93b0-bcec59060308)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/88d9b5cc-18ef-40cc-afa0-f7182306d40d)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/320a5e58-2db9-4ab2-937a-f7cd499f713c)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/c356d694-abeb-4b33-b4d5-aac8ed816c6c)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/f354c382-1f02-4921-afeb-285ac3414ad9)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/34d890af-5068-440f-92a0-eee6131a970b)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/76bb7022-ce12-4593-9c28-2ee01410e36d)
![Image](https://github.com/jpenlan/ARTG-129-Gey_Vampire_Masquerade/assets/132611208/790e49d5-78f1-4bad-a85e-48c81c44931c)

**Comment by MetaToshi** [comment]
- desaturated color palettes, dark tones
