### ISSUE TITLE
catacombs environment concept

### ISSUE THREAD

**Issue by HazyHermit** [jpenlan/ARTG-129-Gey_Vampire_Masquerade#6]

**Comment by MetaToshi** [comment]
![Image](https://user-images.githubusercontent.com/70668378/236723250-2f9269bf-bf36-4feb-9cdf-3e52351c15eb.png)

**Comment by HHound** [comment]
![Image](https://user-images.githubusercontent.com/132611208/236723305-107c50eb-2c6f-4464-b25b-630d77171103.png)
![Image](https://user-images.githubusercontent.com/132611208/236723304-1c8cc75f-7c76-4d56-af20-c5244f412661.png)

**Comment by HHound** [comment]
![Image](https://user-images.githubusercontent.com/132611208/236723819-236e1a1a-5860-4eb4-b363-8ec522af21d1.png)

![Image](https://user-images.githubusercontent.com/132611208/236723677-25118f6b-fea1-4bff-b35a-39b8b07bcdee.png)

![Image](https://user-images.githubusercontent.com/132611208/236723857-8ee321a3-f800-46fb-a8e4-452614630279.png)

Moodboard/Reference Images ^-^
